### PR TITLE
Add WSGI app and health check

### PR DESCRIPTION
**Pull request by willkg**
* adds the infrastructure for the WSGI app using Falcon
* implements the first endpoint which is a health check
* adds basic auth handling (albeit mediocre)
* adds infrastructure for testing the wsgi app
* adds initial settings files for development and testing

This fixes issue #17 and implements some of the bits for issue #15, but doesn't completely implement #15. Mostly I needed something easy to build to have something to test the WSGI app with.

### CODE REVIEW

**Comment by willkg** [comment]
@peterbe You've used Falcon before. Can you take a look at this?

**Comment by willkg** [comment]
This uses WebTest for app testing. Helpful docs are here:

http://webtest.pythonpaste.org/en/latest/testapp.html#making-requests

**Comment by willkg** [comment]
Also, this should pass in travis. It has all the bits it needs.

**Comment by willkg** [comment]
Oo--after this one, I've got enough critical mass that fleshing out the "how do I do things with this?" docs is warranted.

**Comment by willkg** [comment]
The file is there, so I'm not sure why this is failing. I'll look into it.

**Comment by willkg** [comment]
^^^ That should pass Travis. Had a problem where it wasn't importing `antenna` because it had an errant `tox.ini` file (we're not using tox) and I wasn't properly setting `PYTHONPATH` or anything else. This fixes all that and cleans up the `ANTENNA_INI` thing, too.

@peterbe Can you take a look at it?

**Comment by peterbe** [comment]
First of all; it works! Yay!

**Comment by peterbe** [comment]
r+

**Comment by willkg** [comment]
I wrote up a few issues for documentation and something else out of your trials and tribulations with getting this working. I'll work on those later.

Thank you for working through this! I appreciate it!

**Pull request merged**
